"""Playbook runs and steps; tool_runs gain a link to their playbook run.

Grants, as in 0002-0004: the app role may SELECT, INSERT and UPDATE both
tables. No DELETE: like tool runs, playbook history is evidence.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-02 16:00:15.748629+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

APP_ROLE = "sentinel_app"

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playbook_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("playbook_id", sa.String(length=64), nullable=False),
        sa.Column("playbook_name", sa.String(length=128), nullable=False),
        sa.Column("playbook_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target", sa.String(length=512), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("celery_task_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("progress_pct", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("current_step", sa.String(length=64), nullable=True),
        sa.Column("finding_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_severity", sa.String(length=16), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMED_OUT')",
            name=op.f("ck_playbook_runs_status_valid"),
        ),
        sa.CheckConstraint(
            "progress_pct BETWEEN 0 AND 100", name=op.f("ck_playbook_runs_progress_pct_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_playbook_runs_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playbook_runs")),
    )
    op.create_index(
        op.f("ix_playbook_runs_created_at"), "playbook_runs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_playbook_runs_user_id_created_at",
        "playbook_runs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "playbook_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("playbook_run_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("tool_id", sa.String(length=64), nullable=False),
        sa.Column("on_failure", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("tool_run_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "on_failure IN ('stop', 'continue')", name=op.f("ck_playbook_steps_on_failure_valid")
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', 'CANCELLED',"
            " 'TIMED_OUT')",
            name=op.f("ck_playbook_steps_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["playbook_run_id"],
            ["playbook_runs.id"],
            name=op.f("fk_playbook_steps_playbook_run_id_playbook_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tool_run_id"],
            ["tool_runs.id"],
            name=op.f("fk_playbook_steps_tool_run_id_tool_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playbook_steps")),
    )
    op.create_index(
        op.f("ix_playbook_steps_playbook_run_id"),
        "playbook_steps",
        ["playbook_run_id"],
        unique=False,
    )
    op.add_column("tool_runs", sa.Column("playbook_run_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_tool_runs_playbook_run_id"), "tool_runs", ["playbook_run_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_tool_runs_playbook_run_id_playbook_runs"),
        "tool_runs",
        "playbook_runs",
        ["playbook_run_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
                REVOKE ALL ON playbook_runs, playbook_steps FROM {APP_ROLE};
                GRANT SELECT, INSERT, UPDATE ON playbook_runs, playbook_steps TO {APP_ROLE};
            END IF;
        END
        $$
        """  # noqa: S608  (APP_ROLE is a module constant, never input)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_tool_runs_playbook_run_id_playbook_runs"), "tool_runs", type_="foreignkey"
    )
    op.drop_index(op.f("ix_tool_runs_playbook_run_id"), table_name="tool_runs")
    op.drop_column("tool_runs", "playbook_run_id")
    op.drop_index(op.f("ix_playbook_steps_playbook_run_id"), table_name="playbook_steps")
    op.drop_table("playbook_steps")
    op.drop_index("ix_playbook_runs_user_id_created_at", table_name="playbook_runs")
    op.drop_index(op.f("ix_playbook_runs_created_at"), table_name="playbook_runs")
    op.drop_table("playbook_runs")
    # ### end Alembic commands ###
