"""Reports and their stored content (Phase 13).

Grants, as in 0002-0005: the app role may SELECT and INSERT both tables and
UPDATE ``reports`` (status, file metadata). ``report_blobs`` is written once
and never updated, and neither table can be deleted from by the app: an
exported report is a record of what was disclosed and to whom.

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-04 08:42:59.719983+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

APP_ROLE = "sentinel_app"

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("target", sa.String(length=512), nullable=True),
        sa.Column("format", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("celery_task_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filename", sa.String(length=160), nullable=True),
        sa.Column("media_type", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "format IN ('pdf', 'json', 'csv', 'txt')", name=op.f("ck_reports_format_valid")
        ),
        sa.CheckConstraint(
            "source_type IN ('tool_run', 'playbook_run')",
            name=op.f("ck_reports_source_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED')",
            name=op.f("ck_reports_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reports_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_created_at"), "reports", ["created_at"], unique=False)
    op.create_index("ix_reports_source", "reports", ["source_type", "source_id"], unique=False)
    op.create_index(
        "ix_reports_user_id_created_at", "reports", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "report_blobs",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_report_blobs_report_id_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("report_id", name=op.f("pk_report_blobs")),
    )
    # ### end Alembic commands ###
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
                REVOKE ALL ON reports, report_blobs FROM {APP_ROLE};
                GRANT SELECT, INSERT, UPDATE ON reports TO {APP_ROLE};
                GRANT SELECT, INSERT ON report_blobs TO {APP_ROLE};
            END IF;
        END
        $$
        """  # noqa: S608  (APP_ROLE is a module constant, never input)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("report_blobs")
    op.drop_index("ix_reports_user_id_created_at", table_name="reports")
    op.drop_index("ix_reports_source", table_name="reports")
    op.drop_index(op.f("ix_reports_created_at"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
