"""File integrity baselines and their entries (Phase 11, ADR 0015).

Grants, as in 0002-0006:

* ``fim_baselines``: SELECT, INSERT, UPDATE. No DELETE: deleting a baseline
  is a soft delete (``deleted_at``), so the record of who monitored what,
  and who stopped, survives.
* ``fim_baseline_entries``: SELECT, INSERT, DELETE. Entries are bulk data
  (up to FIM_MAX_FILES rows per baseline) and are removed when their
  baseline is deleted. They are never updated: a new state is a new baseline.

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-05 05:04:45.929888+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

APP_ROLE = "sentinel_app"

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fim_baselines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("root", sa.String(length=32), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("excludes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("file_count", sa.Integer(), nullable=False),
        sa.Column("dir_count", sa.Integer(), nullable=False),
        sa.Column("other_count", sa.Integer(), nullable=False),
        sa.Column("total_bytes", sa.BigInteger(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_by_username", sa.String(length=64), nullable=False),
        sa.Column("created_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("schedule_minutes", sa.Integer(), nullable=True),
        sa.Column("last_scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_check_run_id", sa.Uuid(), nullable=True),
        sa.Column("last_check_changes", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "schedule_minutes IS NULL OR schedule_minutes IN (15, 60, 360, 1440)",
            name=op.f("ck_fim_baselines_schedule_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_fim_baselines_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_run_id"],
            ["tool_runs.id"],
            name=op.f("fk_fim_baselines_created_run_id_tool_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["users.id"],
            name=op.f("fk_fim_baselines_deleted_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fim_baselines")),
    )
    op.create_index(
        "ix_fim_baselines_due",
        "fim_baselines",
        ["schedule_minutes", "last_scheduled_at"],
        unique=False,
    )
    op.create_table(
        "fim_baseline_entries",
        sa.Column("baseline_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("mtime_ns", sa.BigInteger(), nullable=False),
        sa.Column("mode", sa.Integer(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("gid", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("link_target", sa.Text(), nullable=True),
        sa.Column("note", sa.String(length=32), nullable=True),
        sa.CheckConstraint(
            "kind IN ('file', 'dir', 'symlink', 'other')",
            name=op.f("ck_fim_baseline_entries_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["baseline_id"],
            ["fim_baselines.id"],
            name=op.f("fk_fim_baseline_entries_baseline_id_fim_baselines"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("baseline_id", "path", name=op.f("pk_fim_baseline_entries")),
    )
    # ### end Alembic commands ###
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
                REVOKE ALL ON fim_baselines, fim_baseline_entries FROM {APP_ROLE};
                GRANT SELECT, INSERT, UPDATE ON fim_baselines TO {APP_ROLE};
                GRANT SELECT, INSERT, DELETE ON fim_baseline_entries TO {APP_ROLE};
            END IF;
        END
        $$
        """  # noqa: S608  (APP_ROLE is a module constant, never input)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fim_baseline_entries")
    op.drop_index("ix_fim_baselines_due", table_name="fim_baselines")
    op.drop_table("fim_baselines")
    # ### end Alembic commands ###
